---
# tasks file for sample-apache
- service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - httpd
    - firewalld
- firewalld:
    service: http
    state: enabled
    immediate: yes
    permanent: yes

- template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart_httpd

