---
- hosts: all
  become: yes
  tasks:
    - sysctl:
        name: vm.swappiness
        value: '5'
        state: present
      when: ansible_facts['memtotal_mb']|int > 2048
    - debug:
        msg: Server memory lesss than 2048MB
      when: ansible_facts['memtotal_mb']|int < 2048
