---
- hosts: localhost
  become: true
  tasks: 
    
    - mount:
        path: /mnt/
        src: /dev/sr0
        fstype: iso9660
        state: present
    
    - file:
        path: /repo
        state: directory
        owner: root
        group: root
    
    - copy:
        src: /mnt/
        dest: /repo
    
    - yum_repository:
        name: BaseOS
        baseurl: file:///repo/BaseOS
        gpgcheck: no
        description: BaseOS repo
    - yum_repository:
        name: AppStream
        baseurl: file:///repo/AppStream
        gpgcheck: no
        description: AppStream repo
