---
- hosts: all
  become: true
  tasks:
    - lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen 80'
        line: 'Listen 8080'
    - firewalld:
        port: 8080/tcp
        state: enabled
        permanent: yes
    - service:
        name: httpd
        state: restarted
