---
- hosts: all
  become: true
  tasks:
    - template:
        src: server.j2
        dest: server.txt
      when: (inventory_hostname in groups['webservers']) or (inventory_hostname in groups['database'])
