---
- hosts: prod
  tasks:
    - yum_repository:
        name: "zabbix-monitoring"
        description: "Zabbix 5.2 Repo"
        enabled: yes
        gpgcheck: no
        file: zabbix
        baseurl: https://repo.zabbix.com/zabbix/5.2/rhel/8/x86_64/

    #- yum:
     #   name: zabbix-agent
      #  state: installed
    - name: Populate service facts
      service_facts:

    - debug:
        var: ansible_facts['services']['zabbix-agent.service']

