---
- hosts: all
  tasks:
    - sysctl:
        name: vm.swappiness
        value: '10'
        state: present
      when: ansible_facts['memtotal_mb'] > 2048
    - fail:
        msg: Availbe RAM is less than 2048
      when: ansible_facts['memtotal_mb'] < 2048
