---
- hosts: all 
  vars_files:
  - secret.yml
  - users.yml
  tasks:
  - user:
      name: "{{ item.name }}"
      password: "{{ pw_developer | password_hash('sha512') }}"
      update_password: on_create
    loop: "{{ users }}"
    when: item.job == "developer" and inventory_hostname in groups['webservers']

  - user:
      name: "{{ item.name }}"
      password: "{{ pw_manager | password_hash('sha512') }}"
      update_password: on_create
    loop: "{{ users }}"
    when: item.job == "manager" and inventory_hostname in groups['proxy']

