---
- hosts: all
  tasks:
    - copy:
        content: "Development"
        dest: /etc/issue
      when: "'dev' in group_names"
    - copy:
        content: "test"
        dest: /etc/issue
      when: "'test' in group_names"
    - copy:
        content: "production"
        dest: /etc/issue
      when: "'prod' in group_names"
