---
- hosts: prod,proxy
  tasks:
    - import_role:
        name: haproxy-role
      vars:
        haproxy_backend_mode: 'http'
        haproxy_backend_balance_method: 'roundrobin'
        haproxy_backend_servers: 
          - name: node4
            address: 192.168.44.153:80
          - name: node5
            address: 192.168.44.152:80
      when: "'proxy' in group_names"
    - firewalld:
        service: http
        state: enabled
        immediate: yes
        permanent: yes
      when: "'proxy' in group_names"
    - import_role:
        name: php-role
      when: "'prod' in group_names"
